apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 2
  selectors:
    matchLabels: 
    app: auth
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 3
    template:
      metadata: 
      labels:
        app: auth
      spec:
        containers:
          - name: auth
            image: swastikgour/auth
            ports:
              - containerPort: 5000
            envFrom:
              - configMpRef:
                name: auth-configmap
              - secretRef:
                name: auth-secret
